Update

diff --git a/.github/workflows/infracost.yml b/.github/workflows/infracost.yml
--- a/.github/workflows/infracost.yml
+++ b/.github/workflows/infracost.yml
@@ -1,95 +1,112 @@
-# The GitHub Actions docs (https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on)
-# describe other options for 'on', 'pull_request' is a good default.
+# Infracost runs on pull requests (PR) and posts PR comments.
+# If you use Infracost Cloud, Infracost also runs on main/master branch pushes so the dashboard is updated.
+# The GitHub Action docs (https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows) describe other trigger options.
 on:
   pull_request:
     types: [opened, synchronize, closed]
   push:
     branches:
-      - master
       - main
+      - master
 
 env:
   # If you use private modules you'll need this env variable to use
   # the same ssh-agent socket value across all jobs & steps.
   SSH_AUTH_SOCK: /tmp/ssh_agent.sock
 jobs:
-  # This stage runs the Infracost CLI and posts the pull request comment
+  # This stage runs the Infracost CLI and posts PR comments.
+  # It also updates PR comments when the PR is updated (synchronize event).
   infracost-pull-request-checks:
     name: Infracost Pull Request Checks
     if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize')
     runs-on: ubuntu-latest
+    permissions:
+      contents: read
+      pull-requests: write # Required to post comments
+    # env:
+      ## If you store Terraform variables or modules in a 3rd party such as (e.g. TFC or Spacelift),
+      ## specify the following so Infracost can automatically retrieve them.
+      ## See https://www.infracost.io/docs/features/terraform_modules/#registry-modules for details.
+      #   INFRACOST_TERRAFORM_CLOUD_TOKEN: ${{ secrets.TFC_TOKEN }}
+      #   INFRACOST_TERRAFORM_CLOUD_HOST: app.terraform.io
     steps:
-    - run: |
-          echo "PR comment ${{ github.event.action }}"
+      # If you use private modules, add an environment variable or secret
+      # called GIT_SSH_KEY with your private key, so Infracost CLI can access
+      # private repositories (similar to how Terraform/Terragrunt does).
+      # - name: add GIT_SSH_KEY
+      #   run: |
+      #     ssh-agent -a $SSH_AUTH_SOCK
+      #     mkdir -p ~/.ssh
+      #     echo "${{ secrets.GIT_SSH_KEY }}" | tr -d '\r' | ssh-add -
+      #     ssh-keyscan github.com >> ~/.ssh/known_hosts
 
-    # permissions:
-    #   contents: read
-    #   # Required to post comments
-    #   pull-requests: write
+      - name: Setup Infracost
+        uses: infracost/actions/setup@v2
+        # See https://github.com/infracost/actions/tree/master/setup for other inputs
+        # If you can't use this action, use Docker image infracost/infracost:ci-0.10
+        with:
+          api-key: ${{ secrets.INFRACOST_API_KEY }}
 
-    # # env:
-    #   # If you're using Terraform Cloud/Enterprise and have variables or private modules stored
-    #   # on there, specify the following to automatically retrieve the variables:
-    #   #   INFRACOST_TERRAFORM_CLOUD_TOKEN: ${{ secrets.TFC_TOKEN }}
-    #   #   INFRACOST_TERRAFORM_CLOUD_HOST: app.terraform.io # Change this if you're using Terraform Enterprise
+      # Checkout the base branch of the pull request (e.g. main/master).
+      - name: Checkout base branch
+        uses: actions/checkout@v4
+        with:
+          ref: '${{ github.event.pull_request.base.ref }}'
 
-    # steps:
-    #   # If you use private modules, add an environment variable or secret
-    #   # called GIT_SSH_KEY with your private key, so Infracost can access
-    #   # private repositories (similar to how Terraform/Terragrunt does).
-    #   # - name: add GIT_SSH_KEY
-    #   #   run: |
-    #   #     ssh-agent -a $SSH_AUTH_SOCK
-    #   #     mkdir -p ~/.ssh
-    #   #     echo "${{ secrets.GIT_SSH_KEY }}" | tr -d '\r' | ssh-add -
-    #   #     ssh-keyscan github.com >> ~/.ssh/known_hosts
+      # Generate Infracost JSON file as the baseline.
+      - name: Generate Infracost cost estimate baseline
+        run: |
+          infracost breakdown --path=. \
+                              --format=json \
+                              --out-file=/tmp/infracost-base.json
 
-    #   - name: Setup Infracost
-    #     uses: infracost/actions/setup@v2
-    #     # See https://github.com/infracost/actions/tree/master/setup for other inputs
-    #     # If you can't use this action, see Docker images in https://infracost.io/cicd
-    #     with:
-    #       api-key: ${{ secrets.INFRACOST_API_KEY }}
+      # Checkout the current PR branch so we can create a diff.
+      - name: Checkout PR branch
+        uses: actions/checkout@v4
 
-    #   # Checkout the base branch of the pull request (e.g. main/master).
-    #   - name: Checkout base branch
-    #     uses: actions/checkout@v3
-    #     with:
-    #       ref: '${{ github.event.pull_request.base.ref }}'
+      # Generate an Infracost diff and save it to a JSON file.
+      - name: Generate Infracost diff
+        run: |
+          infracost diff --path=. \
+                          --format=json \
+                          --compare-to=/tmp/infracost-base.json \
+                          --out-file=/tmp/infracost.json
 
-    #   # Generate Infracost JSON file as the baseline.
-    #   - name: Generate Infracost cost estimate baseline
-    #     run: |
-    #       infracost breakdown --path=. \
-    #                           --format=json \
-    #                           --out-file=/tmp/infracost-base.json
+      # Posts a comment to the PR using the 'update' behavior.
+      # This creates a single comment and updates it. The "quietest" option.
+      # The other valid behaviors are:
+      #   delete-and-new - Delete previous comments and create a new one.
+      #   hide-and-new - Minimize previous comments and create a new one.
+      #   new - Create a new cost estimate comment on every push.
+      # See https://www.infracost.io/docs/features/cli_commands/#comment-on-pull-requests for other options.
+      - name: Post Infracost comment
+        run: |
+            infracost comment github --path=/tmp/infracost.json \
+                                     --repo=$GITHUB_REPOSITORY \
+                                     --github-token=${{ github.token }} \
+                                     --pull-request=${{ github.event.pull_request.number }} \
+                                     --behavior=update
 
-    #   # Checkout the current PR branch so we can create a diff.
-    #   - name: Checkout PR branch
-    #     uses: actions/checkout@v3
+  infracost-default-branch-update:
+    name: Infracost Default Branch Update
+    if: github.event_name == 'push' && (github.ref_name == 'main' || github.ref_name == 'main')
+    runs-on: ubuntu-latest
+    steps:
+      - name: Setup Infracost
+        uses: infracost/actions/setup@v2
+        with:
+          api-key: ${{ secrets.INFRACOST_API_KEY }}
 
-    #   # Generate an Infracost diff and save it to a JSON file.
-    #   - name: Generate Infracost diff
-    #     run: |
-    #       infracost diff --path=. \
-    #                       --format=json \
-    #                       --compare-to=/tmp/infracost-base.json \
-    #                       --out-file=/tmp/infracost.json
+      - name: Checkout main/master branch
+        uses: actions/checkout@v4
 
-    #   # Posts a comment to the PR using the 'update' behavior.
-    #   # This creates a single comment and updates it. The "quietest" option.
-    #   # The other valid behaviors are:
-    #   #   delete-and-new - Delete previous comments and create a new one.
-    #   #   hide-and-new - Minimize previous comments and create a new one.
-    #   #   new - Create a new cost estimate comment on every push.
-    #   # See https://www.infracost.io/docs/features/cli_commands/#comment-on-pull-requests for other options.
-    #   - name: Post Infracost comment
-    #     run: |
-    #         infracost comment github --path=/tmp/infracost.json \
-    #                                  --repo=$GITHUB_REPOSITORY \
-    #                                  --github-token=${{github.token}} \
-    #                                  --pull-request=${{github.event.pull_request.number}} \
-    #                                  --behavior=update
+      - name: Run Infracost on default branch and update Infracost Cloud
+        run: |
+          infracost breakdown --path=. \
+                    --format=json \
+                    --out-file=infracost.json
+
+          infracost upload --path=infracost.json || echo "Always pass main branch runs even if there are policy failures"
 
   infracost-pull-request-status-update:
     name: Infracost PR Status Update
@@ -97,12 +114,15 @@ jobs:
     runs-on: ubuntu-latest
     steps:
     - run: |
-        echo "Updating status of ${{ github.event.pull_request.number }} to ${{ github.event.pull_request.merged }}"
+        PR_STATUS="MERGED"
+        if [[ "${{ github.event.pull_request.merged }}" = false ]; then PR_STATUS="CLOSED"; fi
 
-  infracost-default-branch-update:
-    name: Infracost Default Branch Update
-    if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main')
-    runs-on: ubuntu-latest
-    steps:
-    - run: |
-        echo "Updating default branch"
+        echo "Updating status of PR ${{ github.event.pull_request.number }} to $PR_STATUS"
+        curl \
+          --request POST \
+          --header "Content-Type: application/json" \
+          --header "X-API-Key: $INFRACOST_API_KEY" \
+          --data "{ \"query\": \"mutation {updatePullRequestStatus( url: \\\"${{ github.event.pull_request.html_url }}\\\", status: ${PR_STATUS} )}\" }" \
+          "https://dashboard.api.infracost.io/graphql";
+      env:
+        INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
